on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.16.7

  create-release:
    needs:
      - check-conventional-commits
      - lint-pipeline
      - run-tests
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.16.7
    secrets: inherit

  lint-pipeline:
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@v0.16.7
